version: '3.3'
services:
  dsp:
    restart: always
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"

    stdin_open: true
    tty: true

  server:
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8080:8080"

    stdin_open: true
    tty: true
