version: '3.3'
services:
  dsp:
    container_name: dsp
    # networks: central-driver
    restart: always
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"

    stdin_open: true
    tty: true

  server:
    container_name: server
    # networks: central-driver
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      - BROKER_HOST=twn-pdb.sram.com
      - LINE_NAME=Shifter
      - LINE_IDX=4
    ports:
      - "8080:8080"

    stdin_open: true
    tty: true
